import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { NavbarDemo } from "@/components/NavbarDemo";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        {/* <Navbar /> */}
        <NavbarDemo />
        {children}
      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
